[package]
name = "f1-telemetry-rs"
version = "0.1.0"
authors = ["Mathieu Lemay <mathieu.lemay@broadsign.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "^1.3.4"
getset = "^0.1.0"
